// GRID TYPES
export const SET_SELECTED_TILE = "SET_SELECTED_TILE";
export const SET_HOVER_TILE = "SET_HOVER_TILE";
export const SET_ADJACENT_TILES = "SET_ADJACENT_TILES";
export const SET_TILE_DISTANCE = "SET_TILE_DISTANCE";
export const INITIALIZE_GRID_REFERENCE = "INITIALIZE_GRID_REFERENCE";
export const REGISTER_TILE_REF = "REGISTER_TILE_REF";
export const SET_TILE_CHILD = "SET_TILE_CHILD";

// ENTITY TYPES
export const REGISTER_ENTITY = "REGISTER_ENTITY";

// PLAYER TYPES
export const START_PLAYER = "START_PLAYER";
export const MOVE_PLAYER = "MOVE_PLAYER";

// GAME TYPES
export const SET_MOVE_TYPE = "SET_MOVE_TYPE";
export const SET_PLAYER_TURN = "SET_PLAYER_TURN";
